version: "3.7"

services:
  backend:
    build:
      context: djangobackend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangobackend/:/usr/src/app/
    ports:
      - "8080:8000"
    environment:
      - "DEBUG=${DEBUG}"
      - "SECRET_KEY=${SECRET_KEY}"
      - "DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}"
      - "DATABASE=${DATABASE}"
      - "SQL_ENGINE=${SQL_ENGINE}"
      - "SQL_DATABASE=${SQL_DATABASE}"
      - "SQL_USER=${SQL_USER}"
      - "SQL_PASSWORD=${SQL_PASSWORD}"
      - "SQL_HOST=${SQL_HOST}"
      - "SQL_PORT=${SQL_PORT}"
    networks:
      - main
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_DB=${SQL_DATABASE}"
      - "POSTGRES_USER=${SQL_USER}"
      - "POSTGRES_PASSWORD=${SQL_PASSWORD}"
    networks:
      - main

  nginx:
    build: nginx
    volumes:
      - frontend_build:/var/www/frontend:ro
    ports:
      - "8000:80"
    networks:
      - main
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: vuefrontend
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/frontend/dist

networks:
  main:

volumes:
  postgres_data:
  frontend_build:
